#!/bin/bash

sudoers_d_supported=$(grep "^#includedir /private/etc/sudoers.d$" /etc/sudoers | wc -l | bc)

if [[ $sudoers_d_supported -eq 0 ]]
then
	echo "#includedir /private/etc/sudoers.d" >> /etc/sudoers
fi

exit 0
